### ISSUE TITLE
autotrading

### ISSUE THREAD

**Issue by esepro** [LuKks/iqoption#1]
Hi I'm just testing patterns like engulfing and dark cloud cover and morning star and evening star but I want to trade with margin of safety instead of trading when the candle opens
for example when bullish engulf happens then I want to take trade only when current candle price is less than the high or open price of red candle and when bearish engulf happens then I want to take trade only when current candle price is higher than the low or close price of green candle

 could you give an example of how to place trades like these
<img width="1357" alt="1" src="https://user-images.githubusercontent.com/108810896/181212656-836c73a5-fadc-421c-b13d-a015929feaf0.png">

**Comment by LuKks** [comment]
Hello!

I think that all indicators are calculated locally in the browser, so you will have to re-calculate in Node.js analizing the candles that you receive from the WebSocket.

Currently, you can use the `subscribe` method only for `candle-generated` but I will try soon to add other commands to be able to send trades.

Also, the purpose of this library is to be as simple as possible to get data and do common operations.

By the way, you can use:
```js
broker.ws.json({
  name: 'the-command-name',
  // request_id: 's_' + broker.requestId++,
  local_time: broker.localTime(),
  msg: { ... }
})
```

And
```js
broker.on('message', function (data) {
  console.log(data)
})
```
It will print `authenticated`, `front`, `timeSync`, `heartbeat` and all the WebSocket internal messages. Including responses for your own messages.

That example is very raw, but because the library is simple and tries to be "low-level".

**Comment by esepro** [comment]
thanks I'm parsing the candles and doing the calculations in nodejs looking forward for commands to open trades

**Comment by LuKks** [comment]
Hey! Would you like to try the new version?

**Comment by LuKks** [comment]
Btw, there is breaking changes on the subscribe method, etc. You should see the README.

**Comment by esepro** [comment]
Sorry for late reply yes I tried the new version but I'm getting error
throw new Error('Subscription name invalid (' + name + ')')

**Comment by esepro** [comment]
Sorry for late reply yeah I tried the new version working exactly like I wanted thanks
